apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
spec:
  #list of contaiers
  containers:
  - name: debug
    image: muralisanku/debug:v1
    #here with this line port will not be opened, just for information
    command: ["sleep", "100000"]